// Grainient preset configurations for Zenko

export const GRAINIENT_PRESETS = {
  // Current smooth & balanced
  current: {
    color1: "#7F56D9",
    color2: "#301c5c",
    color3: "#FDB022",
    timeSpeed: 0.6,
    colorBalance: -0.3,
    warpStrength: 0.8,
    warpFrequency: 3,
    warpSpeed: 1.2,
    warpAmplitude: 30,
    blendAngle: 0,
    blendSoftness: 0.1,
    rotationAmount: 300,
    noiseScale: 3,
    grainAmount: 0.12,
    grainScale: 5,
    grainAnimated: true,
    contrast: 1.1,
    gamma: 1,
    saturation: 0.9,
    centerX: 0,
    centerY: 0,
    zoom: 0.9,
  },

  // Dynamic & energetic (based on example)
  energetic: {
    color1: "#7F56D9",
    color2: "#301c5c",
    color3: "#FDB022",
    timeSpeed: 0.5,
    colorBalance: -0.34,
    warpStrength: 1.7,
    warpFrequency: 2.8,
    warpSpeed: 0.7,
    warpAmplitude: 36,
    blendAngle: 0,
    blendSoftness: 0.18,
    rotationAmount: 500,
    noiseScale: 4,
    grainAmount: 0.1,
    grainScale: 6.9,
    grainAnimated: true,
    contrast: 1.5,
    gamma: 1.1,
    saturation: 1,
    centerX: 0,
    centerY: 0,
    zoom: 0.9,
  },

  // Calm & subtle
  calm: {
    color1: "#7F56D9",
    color2: "#301c5c",
    color3: "#B19EEF",
    timeSpeed: 0.3,
    colorBalance: -0.2,
    warpStrength: 0.5,
    warpFrequency: 2,
    warpSpeed: 0.4,
    warpAmplitude: 20,
    blendAngle: 0,
    blendSoftness: 0.25,
    rotationAmount: 200,
    noiseScale: 2,
    grainAmount: 0.08,
    grainScale: 4,
    grainAnimated: true,
    contrast: 1.0,
    gamma: 1,
    saturation: 0.8,
    centerX: 0,
    centerY: 0,
    zoom: 0.9,
  },

  // Bold & vibrant
  vibrant: {
    color1: "#FDB022",
    color2: "#7F56D9",
    color3: "#B19EEF",
    timeSpeed: 0.8,
    colorBalance: 0.2,
    warpStrength: 1.5,
    warpFrequency: 4,
    warpSpeed: 1.5,
    warpAmplitude: 45,
    blendAngle: 0,
    blendSoftness: 0.08,
    rotationAmount: 600,
    noiseScale: 5,
    grainAmount: 0.15,
    grainScale: 7,
    grainAnimated: true,
    contrast: 1.6,
    gamma: 1.2,
    saturation: 1.1,
    centerX: 0,
    centerY: 0,
    zoom: 0.9,
  },

  // Smooth without animated grain
  smooth: {
    color1: "#7F56D9",
    color2: "#301c5c",
    color3: "#FDB022",
    timeSpeed: 0.6,
    colorBalance: -0.3,
    warpStrength: 0.8,
    warpFrequency: 3,
    warpSpeed: 1.2,
    warpAmplitude: 30,
    blendAngle: 0,
    blendSoftness: 0.15,
    rotationAmount: 300,
    noiseScale: 3,
    grainAmount: 0.1,
    grainScale: 5,
    grainAnimated: false, // No grain animation
    contrast: 1.1,
    gamma: 1,
    saturation: 0.9,
    centerX: 0,
    centerY: 0,
    zoom: 0.9,
  },
};
